### ISSUE TITLE
Rarefaction

### ISSUE THREAD

**Issue by himelmallick** [angelolimeta/Gut-microbiome-immunotherapy#1]
Hi @angelolimeta - reapply appreciate the processed data from your JCI paper. I have a quick question - would you be able to clarify if rarefaction was performed at any stage of the analysis? Thanks for your time.

**Comment by angelolimeta** [comment]
Hi @himelmallick! Thanks, hope u can find some good use for it! No, no rarefaction was performed on the data. Do you think it could be useful to add that to the analysis?

**Comment by himelmallick** [comment]
Hi @angelolimeta - we wanted to confirm because a comparison of rarefied and non-rarified results will be useful from a sensitivity analysis point of view. 

Another question: did you use the default settings for mOTUs2 and other functional profiling tools? Again we wanted to confirm if we use the default settings of these tools, the results will be more or less comparable to your paper. Thanks again for your quick response!

**Comment by angelolimeta** [comment]
I see! Yes, default settings were used for mOTUs and HUMAnN2. For HUMAnN2, version 20 of the chochophlan database was used. I saw that the authors behind HUMANnN2 recently moved their repo from bitbucket to github. I only managed to find the latest version of this database (v30). Not sure if you need to exactly replicate the results, using a newer database might improve the analysis. Anyway, in case you need the old one, i have it saved somewhere on our computing cluster and can send it.
Also saw that a new version of humann is available (v3), albeit in late stage alpha.

**Comment by himelmallick** [comment]
Thanks again for confirming! Appreciate your quick response!
