### ISSUE TITLE
Description of WGS Data

### ISSUE THREAD

**Issue by himelmallick** [angelolimeta/Gut-microbiome-immunotherapy#2]
Hi @angelolimeta - apologies for asking too many questions but I noticed that the description of the datasets (studies) does not match between the final published paper and the GitHub repository. Would you be able to confirm if the combined dataset in this repository matches exactly with the most updated version as described in Table 1 of the manuscript? Many thanks again!

**Comment by angelolimeta** [comment]
Hi, sorry for this! I realized i hadn't updated the readme file yet, my bad. Gonna fix this asap. 
The data in this repo contains data from the 4 studies included in the Readme, including the Routy et al. study of RCC and NSCLC patients that we didn't include in the manuscript. Data from the validation cohort (peters et al.) is in the files labeled with "val_" as prefix.
So, all the data from table 1 is in the repo. E.g. for the mOTUs data, which is in the OTU.rds object, just filter out samples belonging to the "Routy et al" study, and then add the val_OTU.rds data as well. I can provide you with a combined OTU table and metadata sometime next week as well!
Best,
Angelo

**Comment by himelmallick** [comment]
Thanks, @angelolimeta! Sounds great! I will look forward to the updated files! We very much appreciate your time!
